# This is an example configuration file for NimbusDb.
# No real secrets are stored in this file.
# Actual secrets are injected through env variables.
# This file just shows your shape of yml based configuration

shardCount: 16
logLevel: "debug"
nats:
  url: tls://nats.ccnp.cloops.in:4222
  creds: "{NATS_CREDS}"
  subjectPrefix: "nimbus"
blob:
  endpoint: "minio-test.servers.cloops.in:9000"
  accessKeyID: "admin"
  secretAccessKey: "{BLOB_SECRET_ACCESS_KEY}"
  useSSL: false
  deleteMarkerCleanupDelayDays: 1
  nonCurrentVersionCleanupDelayDays: 1
db:
  channelBufferSize: 256
